dist: focal
language: python
cache: pip

services:
  - postgresql

addons:
  postgresql: "13"

matrix:
  include:
   - env: TOXENV=py37-dj22-wa211-postgres
     python: 3.7

   - env: TOXENV=py38-dj22-wa211-postgres
     python: 3.8

   - env: TOXENV=py38-dj22-wa211-sqlite
     python: 3.8

   - env: TOXENV=py37-dj30-wa211-postgres
     python: 3.7

   - env: TOXENV=py38-dj30-wa211-postgres
     python: 3.8

   - env: TOXENV=py38-dj31-wa211-postgres
     python: 3.8

   - env: TOXENV=py38-dj31-wa211-sqlite
     python: 3.8

   - env: TOXENV=py38-dj31-wamaster-postgres
     python: 3.8

  allow_failures:
   - env: TOXENV=py38-dj31-wamaster-postgres

install:
  - pip install tox

script:
  - tox
