site_name: Wagtail Localize
theme:
  name: 'cinder'
  custom_dir: docs/theme_overrides
markdown_extensions:
  - codehilite
nav:
  - Home: index.md
  - Getting Started:
      - Setup: setup.md
      - Tutorial: tutorial.md
