site_name: Wagtail Localize
site_url: https://wagtail-localize.org
repo_url: https://github.com/wagtail/wagtail-localize/
theme:
  name: "material"
  custom_dir: docs/theme_overrides
  palette:
    primary: teal
  features:
    - navigation.tabs
    - navigation.sections
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences:
      # Allows us to use mermaid and codehilite together
      # https://stackoverflow.com/questions/61638740/exclude-mermaid-code-blocks-for-highlighting-with-codehilite-mkdocs
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.tabbed
extra_css:
  - stylesheets/mkdocstrings.css
plugins:
  - search
  - mermaid2:
      version: 8.6.4
  - mkdocstrings:
      handlers:
        python:
          selection:
            filters:
              - "!^_"  # exlude all members starting with _
              - "^__init__$"  # but always include __init__ modules and methods
          setup_commands:
            - import os
            - import django
            - os.environ.setdefault("DJANGO_SETTINGS_MODULE", "wagtail_localize.test.settings")
            - django.setup()
  - include-markdown
nav:
  - Home: index.md
  - Tutorial:
    - 1. Project set up: tutorial/1-project-set-up.md
    - 2. Configure Wagtail Localize: tutorial/2-configure-wagtail-localize.md
    - 3. Translating Content: tutorial/3-content.md
    - 4. Translating Templates: tutorial/4-templates.md
  - How To Guides:
    - Installation guide: how-to/installation.md
    - Translatable fields configuration: how-to/field-configuration.md
    - Integrations:
      - Pontoon: how-to/integrations/pontoon.md
      - Machine Translation: how-to/integrations/machine-translation.md
    - Migrate from other translation plugins:
      - wagtailtrans: how-to/migrate/wagtailtrans.md
      - wagtail-modeltranslation: how-to/migrate/wagtail-modeltranslation.md
  - Reference:
    - Translatable Fields: ref/translatable-fields.md
    - Strings: ref/strings.md
    - Segments:
        - Value Types: ref/segments/types.md
        - Extraction: ref/segments/extract.md
        - Ingestion: ref/segments/ingest.md
    - Models:
        - Translation Memory: ref/models/translation-memory.md
        - Translation Management: ref/models/translation-management.md
        - Translatable segments: ref/models/translatable-segments.md
        - Overridable segments: ref/models/overridable-segments.md
        - Overridable segments: ref/models/settings.md
    - Synctree module: ref/synctree.md
  - Explanations:
    - Segments: concept/segments.md
    - Content Paths: concept/content-paths.md
    - Auto-generation of Translatable Fields: concept/translatable-fields-autogen.md
    - Tree Synchronisation: concept/tree-synchronisation.md
