version: 2

jobs:
  flake8:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: pipenv install flake8
      - run: pipenv run flake8 wagtail_localize

  test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: git clone git@github.com:wagtail/django-modelcluster.git
      - run: git clone git@github.com:kaedroho/wagtail.git -b internationalisation

      - type: cache-restore
        key: pipenv

      - run: pipenv install -e .[testing] ./wagtail ./django-modelcluster

      - type: cache-save
        key: pipenv
        paths:
          - "~/.cache/pip"
          - "Pipfile.lock"

      - run: pipenv run python testmanage.py test

  nightly-wagtail-test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: git clone git@github.com:wagtail/django-modelcluster.git
      - run: git clone git@github.com:kaedroho/wagtail.git -b internationalisation
      - run: pipenv install -e .[testing] ./wagtail ./django-modelcluster
      - run: pipenv run python testmanage.py test

workflows:
    version: 2
    test:
      jobs:
        - flake8
        - test

    nightly:
      jobs:
        - nightly-wagtail-test
      triggers:
        - schedule:
            cron: "0 0 * * *"
            filters:
              branches:
                only:
                  - master
