name: Ruff

on:
  push:
    branches:
      - main
      - 'stable/**'
  pull_request:
    branches: [main]

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # keep in sync with .pre-commit-config.yaml
      - run: python -Im pip install --user ruff==0.6.1

      - name: Run ruff
        working-directory: .
        run: ruff check --output-format=github wagtail_localize
